name: news_app
description: A new Flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
#  firebase_auth: ^4.4.0
#  firebase_analytics: ^10.2.0
#  firebase_core: ^2.9.0
#  firebase_crashlytics: ^3.1.0
#  firebase_messaging: ^14.4.0
#  firebase_storage: ^11.1.0
  http: ^0.13.6
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

